checkEvery: 10 # In ticks

messages:
  noPermission: '&cYou don''t have the permission to execute this command'
  usage: '&cUsage: /actionregions reload'
  reloaded: '&aPlugin reloaded'

regions:
  example:
    enter-actions:
      requirements:
        'permission':
          requirement-type: 'HAS_PERMISSION'
          input: 'actionregion.example.join'
      actions:
        - '[MESSAGE] hi'
    leave-actions:
      requirements:
        'permission':
          requirement-type: 'HAS_PERMISSION'
          input: 'actionregion.example.leave'
      actions:
        - '[MESSAGE] bye'